[package]
name = "deb822-tools"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
apt-sources-lists = { git = "https://github.com/CosmicFusion/apt-sources-lists-snapshot" }