[package]
name = "legacy-apt-list-tools-rs"
version = "0.1.2"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
apt-sources-lists = { git = "https://github.com/CosmicFusion/apt-sources-lists-snapshot" }
